# Generated by Django 4.0.2 on 2022-02-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_contact_reference_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('Web service', 'Web service'), ('Customer service', 'Customer service')], default='Customer service', max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for Shipping', 'Out for Shipping'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
    ]
