# Generated by Django 4.0.2 on 2022-02-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_contact_subject_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Out for Shipping', 'Out for Shipping'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
    ]
