# Generated by Django 4.0.2 on 2022-02-22 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_order_message_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='message',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
