# Generated by Django 4.0.2 on 2022-02-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_order_status_alter_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Out for Shipping', 'Out for Shipping')], default='Pending', max_length=150),
        ),
    ]
