# Generated by Django 4.0.2 on 2022-02-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_about_alter_contact_subject_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Out for Shipping', 'Out for Shipping'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
    ]
